[platformio]
default_envs = unor3, esp32doit-devkit-v1, unor4_minima, unor4_wifi

[env]
framework = arduino
lib_deps =
    sirdrako/Utilify@^1.0.0
    https://github.com/PiFou86/UtilifyDigitalInput.git

[env:unor3]
platform = atmelavr
board = uno
monitor_speed = 9600
build_src_filter = +<../examples/unor3/main.cpp> +<**/*.cpp>
lib_deps =
    ${env.lib_deps}

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
monitor_speed = 115200
build_src_filter = +<../examples/esp32/main.cpp> +<**/*.cpp>
lib_deps =
    ${env.lib_deps}
monitor_filters = esp32_exception_decoder

[env:unor4_minima]
platform = renesas-ra
board = uno_r4_minima
monitor_speed = 115200
build_src_filter = +<../examples/esp32/main.cpp> +<**/*.cpp>
lib_deps =
    ${env.lib_deps}

[env:unor4_wifi]
platform = renesas-ra
board = uno_r4_wifi
monitor_speed = 115200
build_src_filter = +<../examples/esp32/main.cpp> +<**/*.cpp>
lib_deps =
    ${env.lib_deps}

[native_test]
platform = native
framework =
build_src_filter = +<**/*.cpp>
lib_compat_mode = off
lib_deps =
test_build_src = true
test_framework = unity
test_filter = test_analog_inputs
build_flags =
    -I test/test_analog_inputs/fakes

[env:native-unor3-tests]
extends = native_test
build_flags =
    ${native_test.build_flags}
    -D ARDUINO_AVR_UNO
    -D ARDUINO_ARCH_AVR
    -D UTILIFY_ANALOG_INPUT_BITS=10

[env:native-esp32-tests]
extends = native_test
build_flags =
    ${native_test.build_flags}
    -D ESP32
    -D ARDUINO_ARCH_ESP32
    -D UTILIFY_ANALOG_INPUT_BITS=12

[env:native-esp32-9bit-tests]
extends = env:native-esp32-tests
build_flags =
    ${native_test.build_flags}
    -D ESP32
    -D ARDUINO_ARCH_ESP32
    -D UTILIFY_ANALOG_INPUT_BITS=9

[env:native-esp32-10bit-tests]
extends = env:native-esp32-tests
build_flags =
    ${native_test.build_flags}
    -D ESP32
    -D ARDUINO_ARCH_ESP32
    -D UTILIFY_ANALOG_INPUT_BITS=10

[env:native-esp32-16bit-tests]
extends = env:native-esp32-tests
build_flags =
    ${native_test.build_flags}
    -D ESP32
    -D ARDUINO_ARCH_ESP32
    -D UTILIFY_ANALOG_INPUT_BITS=16
